# Generated by Django 3.0.5 on 2021-03-23 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('open', 'open'), ('closed', 'closed')], default='open', max_length=6)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('closded_at', models.DateTimeField()),
                ('number', models.IntegerField()),
                ('associated_file', models.ForeignKey(blank=True, max_length=100, on_delete=django.db.models.deletion.PROTECT, related_name='repofile', to='repositories.RepoFile')),
                ('associated_folder', models.ForeignKey(blank=True, max_length=100, on_delete=django.db.models.deletion.PROTECT, related_name='repofolder', to='repositories.RepoFolder')),
                ('associated_loc', models.ForeignKey(blank=True, max_length=100, on_delete=django.db.models.deletion.PROTECT, related_name='issue_loc', to='repositories.RepoFolder')),
                ('repository', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.PROTECT, related_name='issue_repo', to='repositories.Repository')),
            ],
        ),
    ]
