# Generated by Django 3.0.5 on 2021-03-23 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_auto_20210323_0652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='closded_at',
            new_name='closed_at',
        ),
    ]
