# Generated by Django 3.0.5 on 2021-03-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_testissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='testissue',
            name='body',
            field=models.TextField(default='some text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testissue',
            name='number',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testissue',
            name='state',
            field=models.CharField(choices=[('open', 'open'), ('closed', 'closed')], default='open', max_length=6),
        ),
    ]
