# Generated by Django 3.0.5 on 2021-03-28 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0002_auto_20210323_0654'),
        ('issues', '0006_auto_20210328_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='testissue',
            name='repository',
            field=models.ForeignKey(default=1, max_length=100, on_delete=django.db.models.deletion.PROTECT, related_name='testissue_repo', to='repositories.Repository'),
            preserve_default=False,
        ),
    ]
