# Generated by Django 3.0.5 on 2021-03-29 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0008_testissue_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testissue',
            old_name='name',
            new_name='title',
        ),
    ]
