# Generated by Django 3.0.5 on 2021-03-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_auto_20210329_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='testissue',
            name='repository_url',
            field=models.URLField(default='default'),
            preserve_default=False,
        ),
    ]
