# Generated by Django 3.0.5 on 2021-04-07 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0005_auto_20210403_1531'),
        ('issues', '0010_testissue_repository_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testissue',
            name='repository',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='testissue_repo', to='repositories.Repository'),
        ),
    ]
