# Generated by Django 3.0.5 on 2021-04-09 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0011_auto_20210407_0723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='name',
            new_name='title',
        ),
    ]
