# Generated by Django 3.0.5 on 2021-04-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0013_auto_20210409_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='slug',
            field=models.SlugField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
