# Generated by Django 3.0.5 on 2021-04-10 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0005_auto_20210403_1531'),
        ('issues', '0017_auto_20210410_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='associated_loc',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_loc', to='repositories.LineOfCode'),
        ),
    ]
