# Generated by Django 3.0.5 on 2021-04-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0018_auto_20210410_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='stamp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
