# Generated by Django 3.0.5 on 2021-04-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0019_issue_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='stamp',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
