# Generated by Django 3.0.5 on 2021-04-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0020_auto_20210421_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
