# Generated by Django 3.0.5 on 2021-03-23 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('open_issues_count', models.IntegerField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RepoFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=150)),
                ('sha', models.CharField(max_length=40)),
                ('url', models.URLField(max_length=250)),
                ('data_type', models.CharField(choices=[('file', 'file'), ('blob', 'blob'), ('tree', 'tree')], default='blob', max_length=4)),
                ('mode', models.CharField(max_length=100)),
                ('parent_folder', models.ForeignKey(blank=True, max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='folder_self', to='repositories.RepoFolder')),
                ('repository', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='folder_repo', to='repositories.Repository')),
            ],
        ),
        migrations.CreateModel(
            name='RepoFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=150)),
                ('data_type', models.CharField(choices=[('file', 'file'), ('blob', 'blob'), ('tree', 'tree')], default='blob', max_length=4)),
                ('content', models.TextField()),
                ('encoding', models.CharField(choices=[('base64', 'base64')], default='base64', max_length=50)),
                ('size', models.CharField(max_length=10)),
                ('sha', models.CharField(max_length=40)),
                ('url', models.URLField(max_length=250)),
                ('repofolder', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='folder_repo', to='repositories.RepoFolder')),
                ('repository', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='file_repo', to='repositories.Repository')),
            ],
        ),
        migrations.CreateModel(
            name='LineOfCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('line_number', models.IntegerField()),
                ('repofile', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='loc', to='repositories.RepoFile')),
            ],
        ),
    ]
