# Generated by Django 3.0.5 on 2021-03-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0002_auto_20210323_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='url',
            field=models.URLField(default='https://api.github.com/repos/RHAM231-IssueTracker/IssueTrackerSandbox'),
            preserve_default=False,
        ),
    ]
