# Generated by Django 3.0.5 on 2021-04-03 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0003_repository_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repofolder',
            name='parent_folder',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_self', to='repositories.RepoFolder'),
        ),
    ]
