# Generated by Django 3.0.5 on 2021-04-03 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0004_auto_20210403_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repofile',
            old_name='repofolder',
            new_name='parent_folder',
        ),
    ]
