# Generated by Django 3.0.5 on 2021-04-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0006_repository_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='repofolder',
            name='issuetracker_url_path',
            field=models.CharField(default='default path', max_length=150),
            preserve_default=False,
        ),
    ]
