# Generated by Django 3.0.5 on 2021-04-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0007_repofolder_issuetracker_url_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repofolder',
            name='path',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
