# Generated by Django 3.0.5 on 2021-04-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0008_auto_20210429_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repofolder',
            name='path',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
