# Generated by Django 3.0.5 on 2021-04-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0009_auto_20210429_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='repofile',
            name='issuetracker_url_path',
            field=models.CharField(default='default_path', max_length=150),
            preserve_default=False,
        ),
    ]
