# Generated by Django 3.0.5 on 2021-05-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0012_auto_20210502_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineofcode',
            name='path',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
