# Generated by Django 3.0.5 on 2021-05-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0013_lineofcode_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
