# Generated by Django 3.0.5 on 2021-05-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0014_auto_20210515_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineofcode',
            name='content',
            field=models.TextField(),
        ),
    ]
